import type { RegionInfo, CountryName } from "../types";

export const REGIONS: RegionInfo[] = [
  { code: "ALL", nameKo: "전체", nameEn: "Global" },
  // Asia
  { code: "KR", nameKo: "한국", nameEn: "South Korea" },
  { code: "JP", nameKo: "일본", nameEn: "Japan" },
  { code: "CN", nameKo: "중국", nameEn: "China" },
  { code: "TW", nameKo: "대만", nameEn: "Taiwan" },
  { code: "HK", nameKo: "홍콩", nameEn: "Hong Kong" },
  { code: "IN", nameKo: "인도", nameEn: "India" },
  { code: "TH", nameKo: "태국", nameEn: "Thailand" },
  { code: "SG", nameKo: "싱가포르", nameEn: "Singapore" },
  { code: "MY", nameKo: "말레이시아", nameEn: "Malaysia" },
  { code: "PH", nameKo: "필리핀", nameEn: "Philippines" },
  { code: "ID", nameKo: "인도네시아", nameEn: "Indonesia" },
  { code: "VN", nameKo: "베트남", nameEn: "Vietnam" },
  // North America
  { code: "US", nameKo: "미국", nameEn: "United States" },
  { code: "CA", nameKo: "캐나다", nameEn: "Canada" },
  { code: "MX", nameKo: "멕시코", nameEn: "Mexico" },
  // Europe
  { code: "GB", nameKo: "영국", nameEn: "United Kingdom" },
  { code: "FR", nameKo: "프랑스", nameEn: "France" },
  { code: "DE", nameKo: "독일", nameEn: "Germany" },
  { code: "IT", nameKo: "이탈리아", nameEn: "Italy" },
  { code: "ES", nameKo: "스페인", nameEn: "Spain" },
  { code: "PT", nameKo: "포르투갈", nameEn: "Portugal" },
  { code: "NL", nameKo: "네덜란드", nameEn: "Netherlands" },
  { code: "BE", nameKo: "벨기에", nameEn: "Belgium" },
  { code: "AT", nameKo: "오스트리아", nameEn: "Austria" },
  { code: "CH", nameKo: "스위스", nameEn: "Switzerland" },
  { code: "SE", nameKo: "스웨덴", nameEn: "Sweden" },
  { code: "DK", nameKo: "덴마크", nameEn: "Denmark" },
  { code: "NO", nameKo: "노르웨이", nameEn: "Norway" },
  { code: "FI", nameKo: "핀란드", nameEn: "Finland" },
  { code: "PL", nameKo: "폴란드", nameEn: "Poland" },
  { code: "GR", nameKo: "그리스", nameEn: "Greece" },
  { code: "IE", nameKo: "아일랜드", nameEn: "Ireland" },
  { code: "RU", nameKo: "러시아", nameEn: "Russia" },
  { code: "TR", nameKo: "터키", nameEn: "Turkey" },
  // Oceania
  { code: "AU", nameKo: "호주", nameEn: "Australia" },
  { code: "NZ", nameKo: "뉴질랜드", nameEn: "New Zealand" },
  // South America
  { code: "BR", nameKo: "브라질", nameEn: "Brazil" },
  { code: "AR", nameKo: "아르헨티나", nameEn: "Argentina" },
  { code: "CL", nameKo: "칠레", nameEn: "Chile" },
  { code: "CO", nameKo: "콜롬비아", nameEn: "Colombia" },
  { code: "PE", nameKo: "페루", nameEn: "Peru" },
  // Middle East & Africa
  { code: "IL", nameKo: "이스라엘", nameEn: "Israel" },
  { code: "AE", nameKo: "아랍에미리트", nameEn: "UAE" },
  { code: "SA", nameKo: "사우디아라비아", nameEn: "Saudi Arabia" },
  { code: "EG", nameKo: "이집트", nameEn: "Egypt" },
  { code: "ZA", nameKo: "남아프리카", nameEn: "South Africa" },
];

export const COUNTRY_NAMES: Record<string, CountryName> = {
  KR: { ko: "한국", en: "South Korea" },
  US: { ko: "미국", en: "United States" },
  JP: { ko: "일본", en: "Japan" },
  GB: { ko: "영국", en: "United Kingdom" },
  FR: { ko: "프랑스", en: "France" },
  DE: { ko: "독일", en: "Germany" },
  CN: { ko: "중국", en: "China" },
  TW: { ko: "대만", en: "Taiwan" },
  HK: { ko: "홍콩", en: "Hong Kong" },
  IN: { ko: "인도", en: "India" },
  AU: { ko: "호주", en: "Australia" },
  CA: { ko: "캐나다", en: "Canada" },
  IT: { ko: "이탈리아", en: "Italy" },
  ES: { ko: "스페인", en: "Spain" },
  BR: { ko: "브라질", en: "Brazil" },
  MX: { ko: "멕시코", en: "Mexico" },
  RU: { ko: "러시아", en: "Russia" },
  SE: { ko: "스웨덴", en: "Sweden" },
  NL: { ko: "네덜란드", en: "Netherlands" },
  BE: { ko: "벨기에", en: "Belgium" },
  PL: { ko: "폴란드", en: "Poland" },
  TH: { ko: "태국", en: "Thailand" },
  SG: { ko: "싱가포르", en: "Singapore" },
  MY: { ko: "말레이시아", en: "Malaysia" },
  PH: { ko: "필리핀", en: "Philippines" },
  ID: { ko: "인도네시아", en: "Indonesia" },
  VN: { ko: "베트남", en: "Vietnam" },
  NZ: { ko: "뉴질랜드", en: "New Zealand" },
  AR: { ko: "아르헨티나", en: "Argentina" },
  CL: { ko: "칠레", en: "Chile" },
  CO: { ko: "콜롬비아", en: "Colombia" },
  PE: { ko: "페루", en: "Peru" },
  ZA: { ko: "남아프리카", en: "South Africa" },
  EG: { ko: "이집트", en: "Egypt" },
  TR: { ko: "터키", en: "Turkey" },
  GR: { ko: "그리스", en: "Greece" },
  PT: { ko: "포르투갈", en: "Portugal" },
  AT: { ko: "오스트리아", en: "Austria" },
  CH: { ko: "스위스", en: "Switzerland" },
  DK: { ko: "덴마크", en: "Denmark" },
  NO: { ko: "노르웨이", en: "Norway" },
  FI: { ko: "핀란드", en: "Finland" },
  IE: { ko: "아일랜드", en: "Ireland" },
  IL: { ko: "이스라엘", en: "Israel" },
  AE: { ko: "아랍에미리트", en: "UAE" },
  SA: { ko: "사우디아라비아", en: "Saudi Arabia" },
};
